# Generated by Django 4.2.9 on 2024-02-21 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl_comb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(db_comment='Car model description', max_length=50)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ctrl_comb.brand')),
            ],
            options={
                'verbose_name': 'Modelo',
                'verbose_name_plural': 'Modelos',
            },
        ),
    ]
